"""No-Isaac validation of scripts/mppi_controller.py and scripts/eval_mppi.py.

Same three layers as scripts/test_classical_baseline_math.py and
scripts/test_wave_line_cpu.py, none of which launches Isaac Sim:

1. Source hygiene: the two modules AST-parse, contain no control characters
   (ord < 32 other than LF/CR) and no non-ASCII bytes.
2. Argparse path: eval_mppi's parser + pre-flight guards run without Isaac
   (its module top imports stdlib only); every invalid flag set must exit 2.
3. Pure math on CPU:
   - nominal-model integration sanity: forward thrust accelerates in a
     straight line; the drag-limited speed matches usv10k_score.py's V_MAX
     (2.991 m/s) to 1e-3; reverse and yaw terminal rates match closed form;
     sway decays; a hard turn stays inside a bounded turning circle;
   - MPPI convergence on toy scenarios where the WORLD is the same nominal
     model (open-water goals at three bearings, a two-gate chain, a hold
     point, a single-obstacle dodge, a fabricated dock, a fabricated
     three-gate harbor mission ending at a berth);
   - the berthing cost actually discriminates: a wrong-heading arrival costs
     strictly more than a correct one, and a gate crossed from the WRONG
     SIDE earns no credit (checked against the deployed env's own
     tasks/harbor_mission/harbor_geometry.gate_crossing_mask when that
     module is importable beside this one);
   - family detection returns the right mode for each of the five task ids
     the evaluator used to refuse, and still REFUSES on an env exposing
     none of the privileged targets;
   - the STATE BRIDGE hands every family the reference point that family's
     OWN success predicate scores at -- six fabricated envs whose center of
     mass and USD body origin sit 1 m apart, plus a cross-check that
     re-derives the scored point from the deployed env sources so the
     fixtures cannot drift (section 3b-v);
   - the nominal-model disclosure loop reaches the current and the wave
     field, which live BELOW the top-level cfg and used to pass in silence;
   - batched shapes, deterministic sampling given a seed, and no cross-env
     leakage (perturbing env 1's obstacle must not change env 0's action);
   - wall-clock per control step at N_env=64, K=256, H=30 on CPU, with and
     without a 96-obstacle field (the GPU boxes only run faster);
   - per-episode record schema key-diff against eval_v6_frozen.py (the only
     allowed extra key is the "controller" tag, planner-PID precedent).
4. REGRESSION, and the reason this file may be trusted about the 30+
   certified dual-seed numbers already published from gates / hold / goal:
   test_regression_certified_modes_bit_identical replays three fixed
   scenarios and compares the executed actions BIT FOR BIT against hex
   fixtures captured from the pre-dock/mission controller. The fixtures were
   generated on 2026-08-24 from the file as it stood before the docking work
   (CPU, float32, N=2 K=8 H=5, three control steps each) and verified stable
   across torch thread counts; they are not regenerated by this file, so a
   later edit that perturbs the certified cost path fails loudly here.

Run:  python scripts/test_mppi_cpu.py
  or: python -m pytest scripts/test_mppi_cpu.py -v
"""

from __future__ import annotations

import ast
import contextlib
import io
import math
import os
import re
import sys
import time

import torch

_SCRIPTS = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_SCRIPTS)
for path in (_REPO, _SCRIPTS):
    if path not in sys.path:
        sys.path.insert(0, path)

import eval_mppi  # noqa: E402  (stdlib-only module top; no Isaac)
from mppi_controller import (  # noqa: E402
    DOCK_HEADING_TOLERANCE_DEG,
    DOCK_SPEED_TOLERANCE_MPS,
    GATE_HALF_WIDTH_M,
    GATE_MIN_NORMAL_SPEED_MPS,
    MPPIController,
    MPPIParams,
    NOMINAL_BLUEBOAT,
    NominalBlueBoatDynamics,
    terminal_speed,
)

CONTROLLER_PY = os.path.join(_SCRIPTS, "mppi_controller.py")
EVAL_PY = os.path.join(_SCRIPTS, "eval_mppi.py")
FROZEN_EVAL = os.path.join(_SCRIPTS, "eval_v6_frozen.py")
USV10K = os.path.join(_SCRIPTS, "usv10k_score.py")
TASKS_DIR = os.path.join(_REPO, "tasks")
HARBOR_GEOMETRY_PY = os.path.join(
    TASKS_DIR, "harbor_mission", "harbor_geometry.py"
)
DOCKING_ENV_PY = os.path.join(TASKS_DIR, "docking", "docking_env.py")
HARBOR_ENV_PY = os.path.join(TASKS_DIR, "harbor_mission", "harbor_mission_env.py")
SELF = os.path.abspath(__file__)

DEVICE = "cpu"
GOAL_RADIUS = 2.0  # PathFollow/HazardNav goal_radius and StationKeep-BlueBoat
                   # hold_radius are all 2.0 m in the deployed cfgs.
BERTH_RADIUS = 2.5  # Dock/HarborMission success_position_tolerance_m, both
                    # families (docking_env_cfg.py:158, harbor cfg:164-165).
DOCK_DOT_TOLERANCE = math.cos(math.radians(DOCK_HEADING_TOLERANCE_DEG))
DOCK_HOLD_STEPS = 300  # required_hold_time_s 5.0 at the 60 Hz control step.


# ---------------------------------------------------------------- layer 1


def test_source_hygiene():
    for target in (CONTROLLER_PY, EVAL_PY, SELF):
        data = open(target, "rb").read()
        bad = [(i, b) for i, b in enumerate(data)
               if (b < 32 and b not in (10, 13)) or b > 126]
        assert not bad, f"control/non-ascii bytes in {target}: {bad[:5]}"
        ast.parse(data.decode("utf-8"), filename=target)


# ---------------------------------------------------------------- layer 2


def _guard_exit(argv: list[str]) -> int:
    parser = eval_mppi._build_parser()
    try:
        args, _ = parser.parse_known_args(argv)
        eval_mppi._validate_args(parser, args)
    except SystemExit as exc:
        return int(exc.code or 0)
    return -1  # parsed and passed the guards


def test_eval_argparse_guards():
    assert _guard_exit(["--help"]) == 0
    assert _guard_exit([]) == -1  # defaults are a valid configuration
    assert _guard_exit([
        "--task", "Isaac-USV-HazardCross-Direct-v1", "--num_envs", "16",
        "--episodes", "16", "--level", "0", "--eval-seed", "42",
        "--out", "wf_mppi_cross16.json",
    ]) == -1
    assert _guard_exit(["--episodes", "0"]) == 2
    assert _guard_exit(["--num_envs", "0"]) == 2
    assert _guard_exit(["--K", "1"]) == 2
    assert _guard_exit(["--H", "0"]) == 2
    assert _guard_exit(["--sigma-thrust", "0"]) == 2
    assert _guard_exit(["--sigma-yaw", "-0.5"]) == 2
    assert _guard_exit(["--lambda", "0"]) == 2
    assert _guard_exit(["--task", "Isaac-Cartpole-v0"]) == 2
    assert _guard_exit(["--set", "no_equals_sign"]) == 2
    # The two new families are ordinary --task values, not special cases.
    for task in _PREVIOUSLY_REFUSED_IDS:
        assert _guard_exit(["--task", task, "--episodes", "8"]) == -1, task
    assert _guard_exit(["--w-dock-heading", "-0.1"]) == 2
    assert _guard_exit(["--w-dock-speed", "-1"]) == 2
    assert _guard_exit(["--w-dock-heading", "0", "--w-dock-speed", "0"]) == -1


class _FakeEnv:
    """Attribute bag standing in for an Isaac env in _detect_mode only.

    Each fixture below lists the attributes the REAL env of that task id
    publishes; test_detection_fixtures_match_the_real_env_sources checks
    those names against the env sources so this cannot quietly drift into a
    tautology.
    """

    def __init__(self, **attrs):
        for name, value in attrs.items():
            setattr(self, name, value)


# The five ids scripts/eval_mppi.py refused outright before the docking and
# harbor families were added, with the mode each must now resolve to.
_PREVIOUSLY_REFUSED_IDS = (
    "Isaac-USV-Dock-BlueBoat-Direct-v1",
    "Isaac-USV-HarborStage1-Direct-v1",
    "Isaac-USV-HarborStage2-Direct-v1",
    "Isaac-USV-HarborStage3-Direct-v1",
    "Isaac-USV-HarborMission-Direct-v1",
)

# Attribute surface each family really publishes:
#   docking_env.py:67-70          dock_point, dock_heading
#   harbor_mission_env.py:76-96   gate_midpoints, gate_normals, berth_point,
#                                 dock_heading, obstacle_centers/radii/active
#                                 (+ phase at :103)
_DOCK_ATTRS = ("dock_point", "dock_heading")
_MISSION_ATTRS = (
    "gate_midpoints",
    "gate_normals",
    "berth_point",
    "dock_heading",
    "phase",
    "obstacle_centers",
    "obstacle_radii",
    "obstacle_active",
)
_REFUSED_ID_MODES = {
    task: ("dock" if "Dock-" in task else "mission")
    for task in _PREVIOUSLY_REFUSED_IDS
}
# The attributes _detect_mode actually branches on for the two new families.
# The shared obstacle list is excluded on purpose: HazardNav publishes it too.
_DETECTION_KEYS = (
    "dock_point",
    "dock_heading",
    "gate_midpoints",
    "gate_normals",
    "berth_point",
)


def _fake_env_for(task: str) -> _FakeEnv:
    names = _DOCK_ATTRS if "Dock-" in task else _MISSION_ATTRS
    return _FakeEnv(**{name: object() for name in names})


def test_detection_resolves_every_previously_refused_id():
    """The five ids that used to exit in 10 seconds now pick a real cost."""
    for task, expected in _REFUSED_ID_MODES.items():
        got = eval_mppi._detect_mode(_fake_env_for(task))
        assert got == expected, f"{task}: detected {got!r}, want {expected!r}"


def test_detection_keeps_the_three_certified_modes_unchanged():
    """Widened, not replaced: the certified families still map as before."""
    path_follow = _FakeEnv(waypoints=object(), gates_passed=object())
    station_keep = _FakeEnv(hold_point=object())
    hazard_nav = _FakeEnv(
        target_pos=object(), obstacle_centers=object(), obstacle_radii=object()
    )
    assert eval_mppi._detect_mode(path_follow) == "gates"
    assert eval_mppi._detect_mode(station_keep) == "hold"
    assert eval_mppi._detect_mode(hazard_nav) == "goal"
    # No branch can shadow another whatever order they are tested in: the
    # attributes each one keys on are disjoint across families. (The obstacle
    # list is deliberately NOT in this set -- HazardNav and HarborMission
    # both publish it, and neither detects on it.)
    for name in _DETECTION_KEYS:
        assert not hasattr(path_follow, name) and not hasattr(hazard_nav, name)
        assert not hasattr(station_keep, name)
    for name in ("waypoints", "gates_passed", "hold_point", "target_pos"):
        assert not hasattr(_fake_env_for(_PREVIOUSLY_REFUSED_IDS[0]), name)
        assert not hasattr(_fake_env_for(_PREVIOUSLY_REFUSED_IDS[4]), name)


def test_detection_still_refuses_loudly_on_an_unknown_family():
    """No silent fallback: an env with no privileged target must exit."""
    for env in (
        _FakeEnv(),
        _FakeEnv(cfg=object(), robot=object()),
        # Partial docking surface: a point with no heading cannot be berthed.
        _FakeEnv(dock_point=object()),
        # Partial mission surface: gates with no berth are not a mission.
        _FakeEnv(gate_midpoints=object(), gate_normals=object()),
    ):
        try:
            mode = eval_mppi._detect_mode(env)
        except SystemExit as exc:
            message = str(exc)
            assert "not a supported task family" in message, message
            assert "dock_point" in message and "gate_midpoints" in message, (
                "the refusal must name the attributes it looked for: " + message
            )
        else:
            raise AssertionError(f"unknown family was accepted as {mode!r}")


def test_detection_fixtures_match_the_real_env_sources():
    """The fake attribute bags must name attributes the real envs assign.

    Guards against the detection tests above becoming a tautology: every
    attribute _detect_mode keys on is looked up as a literal ``self.<name> =``
    assignment in the deployed env source. Skipped only when tasks/ is not
    deployed beside scripts/ (the boxes ship the pair alone).
    """
    if not (os.path.exists(DOCKING_ENV_PY) and os.path.exists(HARBOR_ENV_PY)):
        print("\n[NOTE] tasks/ not present; env-source cross-check skipped")
        return
    docking = open(DOCKING_ENV_PY, "r", encoding="utf-8").read()
    harbor = open(HARBOR_ENV_PY, "r", encoding="utf-8").read()
    for name in _DOCK_ATTRS:
        assert re.search(rf"self\.{name}\s*=", docking), (
            f"docking_env.py does not assign self.{name}"
        )
    for name in _MISSION_ATTRS:
        assert re.search(rf"self\.{name}\s*=", harbor), (
            f"harbor_mission_env.py does not assign self.{name}"
        )
    # Neither new env may carry a certified family's key either, or the two
    # branches ahead of them would shadow the berthing cost.
    for name in ("waypoints", "gates_passed", "hold_point", "target_pos"):
        assert not re.search(rf"self\.{name}\s*=", docking), name
        assert not re.search(rf"self\.{name}\s*=", harbor), name
    # ...and the three certified envs must not assign any of them, or a new
    # branch could shadow a certified family on a real task id.
    for relative in (
        os.path.join("path_following", "path_following_env.py"),
        os.path.join("station_keeping", "station_keeping_env.py"),
        os.path.join("hazard_nav", "hazard_nav_env.py"),
    ):
        path = os.path.join(TASKS_DIR, relative)
        if not os.path.exists(path):
            continue
        source = open(path, "r", encoding="utf-8").read()
        for name in _DETECTION_KEYS:
            assert not re.search(rf"self\.{name}\s*=", source), (
                f"{relative} now assigns self.{name}; _detect_mode could "
                "route a certified family into a berthing cost"
            )
    # The evaluator reads the exit-gate sub-state to resolve the active leg.
    assert re.search(r"self\._exit_gate_progress\s*=", harbor), (
        "harbor_mission_env.py no longer has _exit_gate_progress; "
        "eval_mppi._mission_leg would silently take its geometric fallback"
    )
    # HarborStage1/2/3 must really be the SAME env and the SAME route as the
    # full mission, differing only in which milestone scores the episode --
    # that claim is why one mission controller drives all four ids.
    cfg_source = open(
        os.path.join(TASKS_DIR, "harbor_mission", "harbor_mission_env_cfg.py"),
        "r",
        encoding="utf-8",
    ).read()
    for stage in (1, 2, 3):
        block = re.search(
            rf"class HarborStage{stage}EnvCfg\(HarborMissionEnvCfg\):(.*?)\n@",
            cfg_source + "\n@",
            re.S,
        )
        assert block, f"HarborStage{stage}EnvCfg is no longer a plain subclass"
        body = block.group(1)
        assert f"mission_depth: int = {stage}" in body, (
            f"HarborStage{stage} no longer scores milestone M{stage}: {body}"
        )
        for forbidden in ("gate_", "berth", "layout_seed", "spawn_phase"):
            assert forbidden not in body, (
                f"HarborStage{stage} overrides {forbidden!r}: the stages are "
                f"no longer prefixes of the same route -- {body}"
            )


def _record_keys(path: str) -> set[str]:
    """All keys the per-episode ``rec`` object can carry, via AST.

    Collects both the ``rec = {...}`` dict literal's string keys and every
    ``rec["key"] = ...`` subscript assignment, anywhere in the module.
    """
    tree = ast.parse(open(path, "r", encoding="utf-8").read(), filename=path)
    keys: set[str] = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if (
                isinstance(target, ast.Name)
                and target.id == "rec"
                and isinstance(node.value, ast.Dict)
            ):
                for key in node.value.keys:
                    if isinstance(key, ast.Constant) and isinstance(key.value, str):
                        keys.add(key.value)
            if (
                isinstance(target, ast.Subscript)
                and isinstance(target.value, ast.Name)
                and target.value.id == "rec"
                and isinstance(target.slice, ast.Constant)
                and isinstance(target.slice.value, str)
            ):
                keys.add(target.slice.value)
    return keys


def test_record_schema_matches_frozen_eval():
    """Per-episode record keys must be the certified schema + controller."""
    frozen = _record_keys(FROZEN_EVAL)
    ours = _record_keys(EVAL_PY)
    assert {"env", "ep", "success", "tts_s", "path_length_m"} <= frozen, (
        f"key extraction from eval_v6_frozen.py looks broken: {sorted(frozen)}"
    )
    assert ours == frozen | {"controller"}, (
        f"record schema drifted: extra={sorted(ours - frozen - {'controller'})}, "
        f"missing={sorted(frozen - ours)}"
    )


def test_eval_parser_defaults_match_controller_defaults():
    """The two files keep literal copies of the defaults; they must agree."""
    args, _ = eval_mppi._build_parser().parse_known_args([])
    params = MPPIParams()
    assert args.K == params.K and args.H == params.H
    assert (args.sigma_thrust, args.sigma_yaw) == tuple(params.sigma)
    assert args.lambda_ == params.lambda_
    assert args.w_goal == params.w_goal
    assert args.w_gate == params.w_gate
    assert args.w_obstacle == params.w_obstacle
    assert args.clearance_margin == params.clearance_margin_m
    assert args.collision_cost == params.collision_cost
    assert args.w_effort == params.w_effort
    assert args.w_terminal == params.w_terminal
    assert args.w_speed_hold == params.w_speed_hold
    assert args.w_dock_heading == params.w_dock_heading
    assert args.w_dock_speed == params.w_dock_speed
    assert args.mppi_seed == params.seed


def test_dock_weight_defaults_match_their_stated_derivation():
    """The two new weights are derived, not fitted -- check the arithmetic.

    Both are quoted at the shipped horizon (H control steps of dt seconds)
    and at the deployed speed tolerance; see the derivation in
    scripts/mppi_controller.py's module docstring.
    """
    params = MPPIParams()
    dt = NOMINAL_BLUEBOAT["physics_dt_s"] * NOMINAL_BLUEBOAT["decimation"]
    v_tol = DOCK_SPEED_TOLERANCE_MPS
    heading = params.w_goal * v_tol * dt * (params.H - 1) / 2.0
    speed = params.w_goal * dt * (params.H - 1) / (2.0 * v_tol)
    assert abs(params.w_dock_heading - heading) < 0.005, (
        f"w_dock_heading {params.w_dock_heading} != derived {heading:.4f}"
    )
    assert abs(params.w_dock_speed - speed) < 0.005, (
        f"w_dock_speed {params.w_dock_speed} != derived {speed:.4f}"
    )
    # The break-even approach speed inside the berth IS the success speed
    # tolerance: at or below 0.3 m/s closing pays, above it slowing pays.
    break_even = dt * (params.H - 1) / (2.0 * params.w_dock_speed)
    assert break_even <= v_tol + 1.0e-3, (
        f"break-even approach speed {break_even:.4f} exceeds the {v_tol} m/s "
        "success tolerance"
    )


# ---------------------------------------------------------------- layer 3
# 3a. Nominal dynamics sanity


def _rest_state(n: int = 1) -> torch.Tensor:
    return torch.zeros((n, 6))


def _drive(dyn, state, action, seconds: float) -> torch.Tensor:
    steps = int(round(seconds / dyn.control_dt_s))
    a = torch.as_tensor(action, dtype=torch.float32).expand(state.shape[0], 2)
    for _ in range(steps):
        state = dyn.step(state, a)
    return state


def test_dynamics_forward_accelerates_and_caps_at_vmax():
    dyn = NominalBlueBoatDynamics(DEVICE)
    s1 = _drive(dyn, _rest_state(), (1.0, 0.0), 1.0)
    assert float(s1[0, 3]) > 1.0, "full thrust should exceed 1 m/s within 1 s"
    s30 = _drive(dyn, s1, (1.0, 0.0), 29.0)
    cap = dyn.terminal_speed_forward()
    assert abs(cap - 2.991) < 1.0e-3, f"closed-form cap {cap} != 2.991"
    assert abs(float(s30[0, 3]) - cap) < 0.01, (
        f"30 s of full thrust reaches {float(s30[0, 3]):.4f}, cap {cap:.4f}"
    )
    # Straight line: no sway, no yaw, no lateral drift.
    assert abs(float(s30[0, 1])) < 1.0e-4
    assert abs(float(s30[0, 2])) < 1.0e-6
    assert abs(float(s30[0, 4])) < 1.0e-4
    # The repo's own number: usv10k_score.py V_MAX.
    match = re.search(r"V_MAX\s*=\s*([0-9.]+)", open(USV10K).read())
    assert match, "V_MAX not found in usv10k_score.py"
    assert abs(cap - float(match.group(1))) < 1.0e-3


def test_dynamics_reverse_cap_and_asymmetry():
    dyn = NominalBlueBoatDynamics(DEVICE)
    s = _drive(dyn, _rest_state(), (-1.0, 0.0), 30.0)
    cap_rev = dyn.terminal_speed_reverse()
    expected = terminal_speed(48.0, 9.1, 5.9)
    assert abs(cap_rev - expected) < 1.0e-9
    assert abs(float(s[0, 3]) + cap_rev) < 0.01
    assert cap_rev < dyn.terminal_speed_forward(), "reverse must be slower"


def test_dynamics_yaw_terminal_rate_and_turning():
    dyn = NominalBlueBoatDynamics(DEVICE)
    s = _drive(dyn, _rest_state(), (0.0, 1.0), 20.0)
    cap_r = dyn.terminal_yaw_rate()
    assert abs(cap_r - terminal_speed(23.0, 4.0, 6.0)) < 1.0e-9
    assert abs(float(s[0, 5]) - cap_r) < 0.005
    assert float(s[0, 2]) > 3.0, "sustained torque must wind up the heading"
    # Thrust + torque = a curved, bounded turning circle.
    s2 = _drive(dyn, _rest_state(), (1.0, 1.0), 40.0)
    radius_bound = dyn.terminal_speed_forward() / cap_r + 1.0
    assert float(s2[0, :2].norm()) < 4.0 * radius_bound, (
        "hard turn should orbit near the start, not run away"
    )
    assert abs(float(s2[0, 1])) > 0.1, "turning must produce lateral motion"


def test_dynamics_sway_decays():
    dyn = NominalBlueBoatDynamics(DEVICE)
    state = _rest_state()
    state[0, 4] = 1.0  # pure sideways slide
    out = _drive(dyn, state, (0.0, 0.0), 5.0)
    assert abs(float(out[0, 4])) < 0.05, "sway drag must kill lateral speed"
    assert float(out[0, 1]) > 0.0, "the slide still moves the hull first"


def test_dynamics_batch_shapes_and_validation():
    dyn = NominalBlueBoatDynamics(DEVICE)
    state = torch.zeros((4, 7, 6))
    action = torch.zeros((4, 7, 2))
    out = dyn.step(state, action)
    assert out.shape == (4, 7, 6)
    try:
        dyn.step(torch.zeros((4, 5)), torch.zeros((4, 2)))
        raise AssertionError("bad state dim must raise")
    except ValueError:
        pass
    try:
        NominalBlueBoatDynamics(DEVICE, params={"not_a_param": 1.0})
        raise AssertionError("unknown param must raise")
    except ValueError:
        pass


# 3b. MPPI behavior on the nominal model as the toy world


def _make_controller(n, K=128, H=None, seed=0, **overrides) -> MPPIController:
    """Production defaults except K=128 for CPU runtime (K=256 only samples
    more richly, so the toys validate the shipped H/sigma/lambda)."""
    if H is None:
        H = MPPIParams().H
    params = MPPIParams(K=K, H=H, seed=seed, **overrides)
    return MPPIController(num_envs=n, device=DEVICE, params=params)


def _run_closed_loop(
    controller,
    state,
    targets,
    mode,
    seconds,
    goal_radius=GOAL_RADIUS,
    obstacle_centers=None,
    obstacle_radii=None,
):
    """Execute MPPI against the nominal model as the world; return history."""
    dyn = controller.dynamics
    steps = int(round(seconds / dyn.control_dt_s))
    n = state.shape[0]
    gates_passed = torch.zeros(n, dtype=torch.long)
    num_gates = targets.shape[1]
    trace = {"dist": [], "pos": [], "speed": [], "gates": []}
    for _ in range(steps):
        active = gates_passed.clamp(max=num_gates - 1)
        action, _info = controller.rollout(
            state,
            targets=targets,
            active_index=active,
            goal_radius=goal_radius,
            mode=mode,
            obstacle_centers=obstacle_centers,
            obstacle_radii=obstacle_radii,
        )
        state = dyn.step(state, action)
        pos = state[:, :2]
        tgt = targets.gather(1, active.reshape(n, 1, 1).expand(n, 1, 2)).squeeze(1)
        dist = (pos - tgt).norm(dim=-1)
        if mode != "hold":  # mirror the env's ordered reach rule
            reached = (dist <= goal_radius) & (gates_passed < num_gates)
            gates_passed = gates_passed + reached.long()
        trace["dist"].append(dist.clone())
        trace["pos"].append(pos.clone())
        trace["speed"].append(state[:, 3:5].norm(dim=-1).clone())
        trace["gates"].append(gates_passed.clone())
    for key in trace:
        trace[key] = torch.stack(trace[key])
    return state, trace


def test_mppi_open_water_goal_convergence():
    """Goals ahead, abeam and astern must all be reached in open water."""
    controller = _make_controller(3)
    state = _rest_state(3)
    targets = torch.tensor(
        [[[9.0, 0.0]], [[0.0, 8.0]], [[-8.0, 0.0]]], dtype=torch.float32
    )
    _final, trace = _run_closed_loop(controller, state, targets, "goal", 15.0)
    min_dist = trace["dist"].min(dim=0).values
    assert bool((min_dist < GOAL_RADIUS).all()), (
        f"open-water goals not all reached: min dist {min_dist.tolist()}"
    )
    reach_step = (trace["dist"] < GOAL_RADIUS).float().argmax(dim=0)
    dt = controller.dynamics.control_dt_s
    assert float(reach_step.max()) * dt < 13.0, (
        f"slowest reach {float(reach_step.max()) * dt:.1f} s is too slow"
    )


def test_mppi_two_gate_chain_passes_through():
    """The gate bonus must beat the park-outside-the-radius pathology."""
    controller = _make_controller(1)
    state = _rest_state(1)
    targets = torch.tensor([[[10.0, 0.0], [10.0, 10.0]]], dtype=torch.float32)
    _final, trace = _run_closed_loop(controller, state, targets, "gates", 20.0)
    assert int(trace["gates"][-1, 0]) == 2, (
        f"gate chain incomplete: passed {int(trace['gates'][-1, 0])}/2"
    )


def test_mppi_station_hold():
    controller = _make_controller(1)
    state = _rest_state(1)
    state[0, 0] = -6.0  # 6 m out, facing the hold point
    targets = torch.zeros((1, 1, 2))
    _final, trace = _run_closed_loop(controller, state, targets, "hold", 20.0)
    tail = int(round(5.0 / controller.dynamics.control_dt_s))
    tail_dist = trace["dist"][-tail:, 0]
    tail_speed = trace["speed"][-tail:, 0]
    assert float(tail_dist.max()) < GOAL_RADIUS, (
        f"hold broken: max distance {float(tail_dist.max()):.2f} m in last 5 s"
    )
    assert float(tail_speed.mean()) < 0.6, (
        f"not settling: mean speed {float(tail_speed.mean()):.2f} m/s"
    )


def test_mppi_obstacle_dodge_no_collision():
    half_beam = NOMINAL_BLUEBOAT["half_beam_m"]
    centers = torch.tensor([[[7.0, 0.3]]], dtype=torch.float32)
    radii = torch.tensor([[1.0]], dtype=torch.float32)
    targets = torch.tensor([[[14.0, 0.0]]], dtype=torch.float32)

    controller = _make_controller(1)
    _final, trace = _run_closed_loop(
        controller, _rest_state(1), targets, "goal", 15.0,
        obstacle_centers=centers, obstacle_radii=radii,
    )
    clearance = (
        (trace["pos"] - centers[0, 0]).norm(dim=-1) - 1.0 - half_beam
    )
    assert float(clearance.min()) > 0.0, (
        f"collision: executed min clearance {float(clearance.min()):.3f} m"
    )
    assert float(trace["dist"].min()) < GOAL_RADIUS, "goal not reached"

    # Ablation: with the obstacle cost off, the straight rush cuts closer.
    blind = _make_controller(1, w_obstacle=0.0, collision_cost=0.0)
    _final_b, trace_b = _run_closed_loop(
        blind, _rest_state(1), targets, "goal", 15.0,
        obstacle_centers=centers, obstacle_radii=radii,
    )
    clearance_b = (
        (trace_b["pos"] - centers[0, 0]).norm(dim=-1) - 1.0 - half_beam
    )
    assert float(clearance_b.min()) < float(clearance.min()), (
        "obstacle cost has no effect on the executed clearance"
    )


def test_mppi_determinism_and_seed_sensitivity():
    state = _rest_state(2)
    state[:, 0] = torch.tensor([0.0, 1.0])
    targets = torch.tensor([[[10.0, 0.0]], [[10.0, 5.0]]], dtype=torch.float32)

    def run(seed):
        controller = _make_controller(2, seed=seed)
        actions = []
        s = state.clone()
        for _ in range(25):
            a, _ = controller.rollout(
                s, targets=targets, active_index=None,
                goal_radius=GOAL_RADIUS, mode="goal",
            )
            s = controller.dynamics.step(s, a)
            actions.append(a.clone())
        return torch.stack(actions)

    a_first = run(7)
    a_second = run(7)
    a_other = run(8)
    assert torch.equal(a_first, a_second), "same seed must reproduce bitwise"
    assert not torch.equal(a_first, a_other), "different seed must differ"


def test_mppi_no_cross_env_leakage():
    """Moving env 1's obstacle must leave env 0's action bitwise unchanged."""
    state = _rest_state(2)
    state[:, 3] = 2.9  # near top speed so the horizon actually reaches 3 m out
    targets = torch.tensor([[[12.0, 0.0]], [[12.0, 0.0]]], dtype=torch.float32)
    radii = torch.tensor([[0.8], [0.8]], dtype=torch.float32)
    far = torch.tensor(
        [[[50.0, 50.0]], [[50.0, 50.0]]], dtype=torch.float32
    )
    near_for_env1 = far.clone()
    near_for_env1[1, 0] = torch.tensor([2.2, 0.0])

    a_base, _ = _make_controller(2, seed=3).rollout(
        state, targets=targets, active_index=None, goal_radius=GOAL_RADIUS,
        mode="goal", obstacle_centers=far, obstacle_radii=radii,
    )
    a_pert, _ = _make_controller(2, seed=3).rollout(
        state, targets=targets, active_index=None, goal_radius=GOAL_RADIUS,
        mode="goal", obstacle_centers=near_for_env1, obstacle_radii=radii,
    )
    assert torch.equal(a_base[0], a_pert[0]), "env 0 leaked env 1's obstacle"
    assert not torch.equal(a_base[1], a_pert[1]), (
        "env 1 ignored its own obstacle move"
    )


def test_mppi_shapes_and_overrides():
    controller = _make_controller(4, K=64, H=20)
    state = _rest_state(4)
    targets = torch.zeros((4, 1, 2))
    targets[:, 0, 0] = 10.0
    action, info = controller.rollout(
        state, targets=targets, active_index=None,
        goal_radius=GOAL_RADIUS, mode="goal",
    )
    assert action.shape == (4, 2)
    assert bool((action >= -1.0).all() and (action <= 1.0).all())
    assert info["ess"].shape == (4,)
    assert controller.U.shape == (4, 20, 2)
    # Spec signature: rollout(state, K, H, sigma, lambda) overrides.
    action2, _ = controller.rollout(
        state, 32, 10, (0.2, 0.4), 5.0,
        targets=targets, active_index=None,
        goal_radius=GOAL_RADIUS, mode="goal",
    )
    assert action2.shape == (4, 2)
    assert controller.U.shape == (4, 10, 2)
    try:
        controller.rollout(
            torch.zeros((3, 6)), targets=targets, active_index=None,
            goal_radius=GOAL_RADIUS, mode="goal",
        )
        raise AssertionError("wrong num_envs must raise")
    except ValueError:
        pass
    try:
        controller.rollout(
            state, targets=targets, active_index=None,
            goal_radius=GOAL_RADIUS, mode="not_a_mode",
        )
        raise AssertionError("bad mode must raise")
    except ValueError:
        pass


def test_mppi_reset_clears_only_done_envs():
    controller = _make_controller(3)
    controller.U += 0.5
    controller.reset(torch.tensor([True, False, True]))
    assert float(controller.U[0].abs().max()) == 0.0
    assert float(controller.U[2].abs().max()) == 0.0
    assert float(controller.U[1].abs().max()) > 0.0


# 3b-ii. Docking (mode="dock") and the ordered harbor mission (mode="mission")


def _dock_success_mask(state, dock_point, dock_heading):
    """The env's berthing conjunction, replicated on the toy state.

    docking_env.py:646-658 -- COM inside success_position_tolerance_m AND the
    bow within success_heading_tolerance_deg of dock_heading AND planar speed
    at or under success_speed_tolerance_mps. harbor_mission_env.py:785-794 is
    the same three lines. Success additionally needs the conjunction held for
    required_hold_time_s, which the callers below count in control steps.
    """
    distance = (state[:, :2] - dock_point).norm(dim=-1)
    forward = torch.stack((torch.cos(state[:, 2]), torch.sin(state[:, 2])), -1)
    dock_dot = (forward * dock_heading).sum(dim=-1)
    speed = state[:, 3:5].norm(dim=-1)
    return (
        (distance <= BERTH_RADIUS)
        & (dock_dot >= DOCK_DOT_TOLERANCE)
        & (speed <= DOCK_SPEED_TOLERANCE_MPS)
    )


def _longest_hold(flags):
    """Longest run of consecutive True per column of a [T, N] bool tensor."""
    best = torch.zeros(flags.shape[1], dtype=torch.long)
    run = torch.zeros(flags.shape[1], dtype=torch.long)
    for row in flags:
        run = torch.where(row, run + 1, torch.zeros_like(run))
        best = torch.maximum(best, run)
    return best


def _spawn_on_approach_lane(dock_point, dock_heading, distance, bearing_deg,
                            heading_offset_deg):
    """One docking spawn, drawn the way docking_env.py:855-901 draws them."""
    bearing = math.radians(bearing_deg)
    base = math.atan2(float(dock_heading[1]), float(dock_heading[0]))
    direction = torch.tensor(
        [math.cos(base + bearing), math.sin(base + bearing)], dtype=torch.float32
    )
    position = dock_point - distance * direction
    return torch.tensor(
        [position[0], position[1], base + math.radians(heading_offset_deg),
         0.0, 0.0, 0.0],
        dtype=torch.float32,
    )


def test_mppi_dock_converges_on_a_fabricated_dock():
    """Reach the berth AND hold the full conjunction for the required 5 s."""
    dock_point = torch.zeros((3, 2))
    dock_heading = torch.tensor([[1.0, 0.0]]).repeat(3, 1)
    state = torch.stack([
        _spawn_on_approach_lane(dock_point[0], dock_heading[0], d, b, h)
        for d, b, h in ((12.0, 0.0, 0.0), (10.0, 60.0, 45.0), (8.0, -30.0, -40.0))
    ])
    controller = _make_controller(3, K=64)
    dyn = controller.dynamics
    steps = int(round(30.0 / dyn.control_dt_s))
    flags = []
    for _ in range(steps):
        action, _info = controller.rollout(
            state, targets=dock_point[:, None, :], active_index=None,
            goal_radius=BERTH_RADIUS, mode="dock", dock_heading=dock_heading,
        )
        state = dyn.step(state, action)
        flags.append(_dock_success_mask(state, dock_point, dock_heading))
    hold = _longest_hold(torch.stack(flags))
    assert bool((hold >= DOCK_HOLD_STEPS).all()), (
        f"berthing hold too short: {(hold * dyn.control_dt_s).tolist()} s of "
        f"the required {DOCK_HOLD_STEPS * dyn.control_dt_s} s"
    )
    # And it ends parked, not merely passing through.
    final = _dock_success_mask(state, dock_point, dock_heading)
    assert bool(final.all()), "boat left the berth pose by the end"


def test_mppi_dock_wrong_heading_costs_more_than_correct():
    """Arriving pointed the wrong way must be strictly more expensive.

    Same position, same speed, same seed and therefore the same sampled
    action sequences: the ONLY difference is the bow direction, so the cost
    gap is attributable to the heading term and to nothing else. The second
    half re-runs both with w_dock_heading = 0 and asserts the gap collapses,
    which pins the cause on that weight rather than on the geometry.
    """
    dock_point = torch.zeros((1, 2))
    dock_heading = torch.tensor([[1.0, 0.0]])
    aligned = torch.tensor([[-1.0, 0.0, 0.0, 0.0, 0.0, 0.0]])
    reversed_bow = torch.tensor([[-1.0, 0.0, math.pi, 0.0, 0.0, 0.0]])

    def cost(state, **overrides):
        controller = _make_controller(1, K=64, seed=5, **overrides)
        _action, info = controller.rollout(
            state, targets=dock_point[:, None, :], active_index=None,
            goal_radius=BERTH_RADIUS, mode="dock", dock_heading=dock_heading,
        )
        return float(info["cost_min"][0])

    gap = cost(reversed_bow) - cost(aligned)
    assert gap > 0.0, f"a reversed bow is not penalised at all (gap {gap:.3f})"
    flat = cost(reversed_bow, w_dock_heading=0.0) - cost(
        aligned, w_dock_heading=0.0
    )
    assert gap > flat + 1.0, (
        f"heading gap {gap:.3f} is not driven by w_dock_heading "
        f"(gap with the weight off: {flat:.3f})"
    )
    # A fast arrival is likewise worse than a slow one, at the same pose.
    slow = torch.tensor([[-1.0, 0.0, 0.0, 0.2, 0.0, 0.0]])
    fast = torch.tensor([[-1.0, 0.0, 0.0, 2.5, 0.0, 0.0]])
    assert cost(fast) > cost(slow), "arriving fast is not penalised"
    assert cost(fast) - cost(slow) > (
        cost(fast, w_dock_speed=0.0) - cost(slow, w_dock_speed=0.0)
    ), "the approach-speed gap is not driven by w_dock_speed"


def _gate_crossed_local(previous, current, velocity, midpoint, normal, armed,
                        half_width_m=GATE_HALF_WIDTH_M,
                        min_normal_speed_mps=GATE_MIN_NORMAL_SPEED_MPS):
    """Independent transcription of the env's gate rule, for the toy loop.

    Kept honest by test_gate_rule_matches_the_deployed_harbor_geometry, which
    diffs it against tasks/harbor_mission/harbor_geometry.gate_crossing_mask.
    """
    previous_signed = ((previous - midpoint) * normal).sum(dim=-1)
    current_signed = ((current - midpoint) * normal).sum(dim=-1)
    denominator = current_signed - previous_signed
    straddles = (
        (previous_signed <= 0.0) & (current_signed >= 0.0) & (denominator > 1.0e-9)
    )
    fraction = torch.where(
        straddles,
        -previous_signed / denominator.clamp_min(1.0e-9),
        torch.zeros_like(denominator),
    )
    intersection = previous + fraction.unsqueeze(-1) * (current - previous)
    tangent = torch.stack((-normal[..., 1], normal[..., 0]), dim=-1)
    lateral = ((intersection - midpoint) * tangent).sum(dim=-1).abs()
    normal_speed = (velocity * normal).sum(dim=-1)
    return (
        armed
        & straddles
        & (lateral <= half_width_m)
        & (normal_speed > min_normal_speed_mps)
    )


def _load_harbor_geometry():
    """Import the deployed gate oracle by path, or None if tasks/ is absent."""
    if not os.path.exists(HARBOR_GEOMETRY_PY):
        return None
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "usvbench_harbor_geometry", HARBOR_GEOMETRY_PY
    )
    module = importlib.util.module_from_spec(spec)
    sys.modules["usvbench_harbor_geometry"] = module
    spec.loader.exec_module(module)
    return module


def test_gate_rule_matches_the_deployed_harbor_geometry():
    """Diff the toy's gate rule against the env's own gate_crossing_mask.

    Rows: a clean forward crossing; the SAME transit against a flipped normal
    (i.e. approached from the wrong side); a crossing outside the 3 m window;
    one under the 0.2 m/s normal-speed floor; and one that never armed.
    """
    geometry = _load_harbor_geometry()
    if geometry is None:
        print("\n[NOTE] tasks/harbor_mission absent; gate-rule diff skipped")
        return
    midpoint = torch.zeros((5, 2))
    normal = torch.tensor([[1.0, 0.0]]).repeat(5, 1)
    normal[1] = torch.tensor([-1.0, 0.0])
    previous = torch.tensor([
        [-0.20, 0.0], [-0.20, 0.0], [-0.20, 5.0], [-0.002, 0.0], [-0.20, 0.0],
    ])
    current = torch.tensor([
        [0.20, 0.0], [0.20, 0.0], [0.20, 5.0], [0.002, 0.0], [0.20, 0.0],
    ])
    velocity = torch.tensor([
        [2.0, 0.0], [2.0, 0.0], [2.0, 0.0], [0.10, 0.0], [2.0, 0.0],
    ])
    armed = torch.tensor([True, True, True, True, False])
    expected = torch.tensor([True, False, False, False, False])
    mine = _gate_crossed_local(previous, current, velocity, midpoint, normal, armed)
    theirs = geometry.gate_crossing_mask(
        previous, current, velocity, midpoint, normal, armed,
        half_width_m=geometry.GATE_HALF_WIDTH_M,
        min_normal_speed_mps=geometry.GATE_MIN_NORMAL_SPEED_MPS,
    )
    assert torch.equal(mine, expected), f"toy rule wrong: {mine.tolist()}"
    assert torch.equal(theirs, expected), f"env rule drifted: {theirs.tolist()}"
    # The constants the controller ships must be the deployed ones.
    assert GATE_HALF_WIDTH_M == geometry.GATE_HALF_WIDTH_M
    assert GATE_MIN_NORMAL_SPEED_MPS == geometry.GATE_MIN_NORMAL_SPEED_MPS
    # And consecutive gates really are far enough apart that the 1 m approach
    # latch is never the binding condition -- the assumption the rollout's
    # gate credit rests on (mppi_controller.py module docstring).
    separation = geometry.EXIT_GATE_X_M[1] - geometry.EXIT_GATE_X_M[0]
    assert separation >= geometry.GATE_APPROACH_DISTANCE_M, separation
    assert (
        geometry.FIELD_START_X_M - geometry.EXIT_GATE_X_M[1]
        >= geometry.GATE_APPROACH_DISTANCE_M
    )


def test_mppi_mission_runs_the_ordered_chain_and_berths():
    """Three ordered gates then a berth, on the env's own crossing rule.

    Gate legs advance here ONLY when _gate_crossed_local fires, i.e. only
    when the deployed env would have credited the crossing, so "the chain
    completed" is not the controller marking its own homework.
    """
    gates = torch.tensor([[[5.0, 0.0], [15.0, 0.0], [30.0, 0.0]]])
    normals = torch.tensor([[[1.0, 0.0], [1.0, 0.0], [1.0, 0.0]]])
    berth = torch.tensor([[45.0, 0.0]])
    dock_heading = torch.tensor([[1.0, 0.0]])
    route = torch.cat((gates, berth[:, None, :]), dim=1)
    centers = torch.tensor([[[21.0, 0.6], [26.0, -1.3]]])
    radii = torch.tensor([[1.4, 1.2]])

    controller = _make_controller(1, K=64)
    dyn = controller.dynamics
    state = torch.zeros((1, 6))
    leg = torch.zeros(1, dtype=torch.long)
    armed = torch.ones(1, dtype=torch.bool)  # spawn is 5 m before gate 0
    previous = state[:, :2].clone()
    crossings = []
    holds = []
    clearance = math.inf
    for _ in range(int(round(45.0 / dyn.control_dt_s))):
        action, _info = controller.rollout(
            state, targets=route, active_index=leg, goal_radius=BERTH_RADIUS,
            mode="mission", dock_heading=dock_heading, gate_normals=normals,
            obstacle_centers=centers, obstacle_radii=radii,
        )
        state = dyn.step(state, action)
        current = state[:, :2]
        cos_y, sin_y = torch.cos(state[:, 2]), torch.sin(state[:, 2])
        world_v = torch.stack(
            (state[:, 3] * cos_y - state[:, 4] * sin_y,
             state[:, 3] * sin_y + state[:, 4] * cos_y), dim=-1
        )
        clearance = min(clearance, float(
            (current - centers[0]).norm(dim=-1).min()
            - radii.min() - NOMINAL_BLUEBOAT["half_beam_m"]
        ))
        index = int(leg[0])
        if index < 3:
            armed = armed | (
                ((previous - gates[:, index]) * normals[:, index]).sum(-1) <= -1.0
            )
            if bool(_gate_crossed_local(
                previous, current, world_v, gates[:, index], normals[:, index],
                armed,
            )[0]):
                crossings.append(index)
                leg = leg + 1
                nxt = int(leg[0])
                armed = torch.zeros(1, dtype=torch.bool)
                if nxt < 3:
                    armed = armed | (
                        ((current - gates[:, nxt]) * normals[:, nxt]).sum(-1) <= -1.0
                    )
        else:
            holds.append(_dock_success_mask(state, berth, dock_heading))
        previous = current.clone()

    assert crossings == [0, 1, 2], (
        f"ordered chain incomplete or out of order: credited {crossings}"
    )
    assert holds, "the mission never reached its berth leg"
    hold = int(_longest_hold(torch.stack(holds))[0])
    assert hold >= DOCK_HOLD_STEPS, (
        f"berth hold {hold * dyn.control_dt_s:.1f} s of the required "
        f"{DOCK_HOLD_STEPS * dyn.control_dt_s} s"
    )
    assert clearance > 0.0, f"hit the field: min clearance {clearance:.3f} m"


def test_mppi_mission_wrong_side_crossing_earns_no_credit():
    """Flip the gate normal and the same transit stops being a crossing.

    Identical state, identical targets, identical seed and therefore
    identical sampled action sequences; the only change is the SIGN of the
    gate normal, which turns a forward transit into an approach from the
    wrong side. The w_gate credit must vanish with it.
    """
    gate = torch.tensor([[0.0, 0.0]])
    berth = torch.tensor([[20.0, 0.0]])
    route = torch.cat((gate[:, None, :], berth[:, None, :]), dim=1)
    dock_heading = torch.tensor([[1.0, 0.0]])
    state = torch.tensor([[-0.3, 0.0, 0.0, 2.0, 0.0, 0.0]])

    def cost(normal_sign):
        controller = _make_controller(1, K=64, H=20, seed=9)
        _action, info = controller.rollout(
            state, targets=route, active_index=torch.zeros(1, dtype=torch.long),
            goal_radius=BERTH_RADIUS, mode="mission",
            dock_heading=dock_heading,
            gate_normals=torch.tensor([[[normal_sign, 0.0]]]),
        )
        return float(info["cost_min"][0])

    right_way = cost(1.0)
    wrong_way = cost(-1.0)
    params = MPPIParams()
    assert wrong_way - right_way > 0.5 * params.w_gate, (
        f"wrong-side crossing was credited: cost {wrong_way:.2f} vs "
        f"{right_way:.2f} the right way round (w_gate={params.w_gate})"
    )
    # The toy's own rule agrees: same samples, opposite verdict.
    forward = _gate_crossed_local(
        torch.tensor([[-0.3, 0.0]]), torch.tensor([[0.3, 0.0]]),
        torch.tensor([[2.0, 0.0]]), gate, torch.tensor([[1.0, 0.0]]),
        torch.ones(1, dtype=torch.bool),
    )
    backward = _gate_crossed_local(
        torch.tensor([[-0.3, 0.0]]), torch.tensor([[0.3, 0.0]]),
        torch.tensor([[2.0, 0.0]]), gate, torch.tensor([[-1.0, 0.0]]),
        torch.ones(1, dtype=torch.bool),
    )
    assert bool(forward[0]) and not bool(backward[0])


def _mission_gate_cost(state, *, half_width=GATE_HALF_WIDTH_M,
                       min_normal_speed=GATE_MIN_NORMAL_SPEED_MPS):
    """Best rollout cost for one mission step at a single gate, fixed seed.

    One gate at the origin with a +x normal, then a berth 20 m on. Same seed,
    same K/H, same geometry -> the SAME sampled action sequences, so a cost
    difference between two calls is attributable only to the keyword that
    changed.
    """
    gate = torch.zeros((1, 2))
    berth = torch.tensor([[20.0, 0.0]])
    route = torch.cat((gate[:, None, :], berth[:, None, :]), dim=1)
    controller = _make_controller(1, K=64, H=20, seed=9)
    _action, info = controller.rollout(
        state, targets=route, active_index=torch.zeros(1, dtype=torch.long),
        goal_radius=BERTH_RADIUS, mode="mission",
        dock_heading=torch.tensor([[1.0, 0.0]]),
        gate_normals=torch.tensor([[[1.0, 0.0]]]),
        gate_half_width_m=half_width,
        gate_min_normal_speed_mps=min_normal_speed,
    )
    return float(info["cost_min"][0])


def test_mppi_mission_gate_half_width_window_is_load_bearing():
    """The gate is a finite SEGMENT, not an infinite plane.

    mppi_controller.py inlines the env's crossing rule
    (harbor_geometry.gate_crossing_mask:175-223) as a conjunction, and the
    ``lateral <= half_width`` term was untested: deleting it left every
    mission test green. Here the only thing that changes between two calls is
    gate_half_width_m, which the controller reads in that one comparison and
    nowhere else, so deleting the term collapses the gap to exactly zero.

    Row 1: the boat crosses 2 m off the gate centre. A 6 m window credits it,
    a 0.5 m window does not, and the missing w_gate credit shows up in the
    cost. Row 2 is the control: crossing dead centre is inside BOTH windows,
    so the two calls must be bit-identical -- which is what makes the term a
    window and not a blanket veto.
    """
    off_centre = torch.tensor([[-0.3, 2.0, 0.0, 2.0, 0.0, 0.0]])
    centred = torch.tensor([[-0.3, 0.0, 0.0, 2.0, 0.0, 0.0]])
    w_gate = MPPIParams().w_gate

    narrow = _mission_gate_cost(off_centre, half_width=0.5)
    wide = _mission_gate_cost(off_centre, half_width=6.0)
    assert narrow - wide > 0.5 * w_gate, (
        f"a crossing 2.0 m off centre is credited through a 0.5 m window: "
        f"cost {narrow:.2f} narrow vs {wide:.2f} wide (w_gate={w_gate})"
    )
    assert _mission_gate_cost(centred, half_width=0.5) == _mission_gate_cost(
        centred, half_width=6.0
    ), "the window is vetoing a crossing that is inside both half-widths"


def test_mppi_mission_gate_normal_speed_floor_is_load_bearing():
    """Drifting through the plane is not a crossing.

    The other untested conjunct: ``normal_speed > min_normal_speed``. Same
    construction -- gate_min_normal_speed_mps is read in that one comparison
    and nowhere else, so deleting the term makes the gap exactly zero.

    Row 1: a 2 m/s transit is credited at the deployed 0.20 m/s floor and
    refused at an unreachable 50 m/s one. Row 2 is the control: from 30 m
    out no sampled rollout reaches the plane inside the horizon at all, so
    the floor cannot change anything and the two calls must be bit-identical.
    """
    transit = torch.tensor([[-0.3, 0.0, 0.0, 2.0, 0.0, 0.0]])
    out_of_reach = torch.tensor([[-30.0, 0.0, 0.0, 0.0, 0.0, 0.0]])
    w_gate = MPPIParams().w_gate

    blocked = _mission_gate_cost(transit, min_normal_speed=50.0)
    credited = _mission_gate_cost(transit, min_normal_speed=GATE_MIN_NORMAL_SPEED_MPS)
    assert blocked - credited > 0.5 * w_gate, (
        f"the normal-speed floor is not consulted: cost {blocked:.2f} at a "
        f"50 m/s floor vs {credited:.2f} at the deployed "
        f"{GATE_MIN_NORMAL_SPEED_MPS} m/s (w_gate={w_gate})"
    )
    assert _mission_gate_cost(
        out_of_reach, min_normal_speed=50.0
    ) == _mission_gate_cost(
        out_of_reach, min_normal_speed=GATE_MIN_NORMAL_SPEED_MPS
    ), "the floor changes the cost even where nothing crosses the plane"


def test_mppi_new_modes_validate_their_required_inputs():
    """dock and mission must refuse to run half-specified, not guess."""
    controller = _make_controller(1, K=16, H=5)
    state = _rest_state(1)
    one = torch.zeros((1, 1, 2))
    two = torch.zeros((1, 2, 2))
    heading = torch.tensor([[1.0, 0.0]])
    normals = torch.zeros((1, 1, 2))
    normals[0, 0, 0] = 1.0
    bad_calls = (
        # dock without a dock_heading
        dict(targets=one, mode="dock"),
        # dock with a whole gate chain instead of one berth
        dict(targets=two, mode="dock", dock_heading=heading),
        # dock_heading of the wrong shape
        dict(targets=one, mode="dock", dock_heading=torch.zeros((1, 3))),
        # mission without gate normals
        dict(targets=two, mode="mission", dock_heading=heading),
        # mission normals that do not match the gate count
        dict(targets=two, mode="mission", dock_heading=heading,
             gate_normals=torch.zeros((1, 2, 2))),
        # mission with a berth but no gate at all
        dict(targets=one, mode="mission", dock_heading=heading,
             gate_normals=normals),
    )
    for kwargs in bad_calls:
        try:
            controller.rollout(
                state, active_index=None, goal_radius=BERTH_RADIUS, **kwargs
            )
        except ValueError:
            continue
        raise AssertionError(f"under-specified call accepted: {kwargs}")
    # The fully specified calls do run.
    action, _ = controller.rollout(
        state, targets=one, active_index=None, goal_radius=BERTH_RADIUS,
        mode="dock", dock_heading=heading,
    )
    assert action.shape == (1, 2)
    action, _ = controller.rollout(
        state, targets=two, active_index=None, goal_radius=BERTH_RADIUS,
        mode="mission", dock_heading=heading, gate_normals=normals,
    )
    assert action.shape == (1, 2)


# 3b-iv. EnvBridge wiring for the two new families (no Isaac, stub envs)


class _StubCfg:
    goal_radius = 2.5
    success_position_tolerance_m = 2.5
    success_heading_tolerance_deg = 15.0
    success_speed_tolerance_mps = 0.3
    gate_half_width_m = 3.0
    gate_min_normal_speed_mps = 0.2


class _StubData:
    def __init__(self, com_xy, origin_xy, yaw, velocity, yaw_rate):
        n = com_xy.shape[0]
        self.root_com_pos_w = torch.cat((com_xy, torch.zeros((n, 1))), dim=1)
        # The USD origin deliberately offset from the COM, as in the assets.
        self.root_pos_w = self.root_com_pos_w + torch.tensor([1.0, 0.0, 0.0])
        self.root_com_vel_w = torch.cat(
            (velocity, torch.zeros((n, 1)), torch.zeros((n, 2)),
             yaw_rate.reshape(n, 1)), dim=1
        )
        self.root_ang_vel_w = torch.zeros((n, 3))
        self.root_ang_vel_w[:, 2] = yaw_rate
        self._yaw = yaw
        self._origin = origin_xy


class _StubRobot:
    def __init__(self, data):
        self.data = data


class _StubBerthEnv:
    """Minimal stand-in exposing exactly what EnvBridge reads."""

    def __init__(self, mode, com_xy, yaw, velocity=None, yaw_rate=None,
                 phase=None, exit_progress=None, publish_exit_progress=True):
        n = com_xy.shape[0]
        velocity = torch.zeros((n, 2)) if velocity is None else velocity
        yaw_rate = torch.zeros(n) if yaw_rate is None else yaw_rate
        self.cfg = _StubCfg()
        self.robot = _StubRobot(
            _StubData(com_xy, torch.zeros((n, 2)), yaw, velocity, yaw_rate)
        )
        self._yaw = yaw
        if mode == "dock":
            self.dock_point = torch.zeros((n, 2))
            self.dock_heading = torch.tensor([[1.0, 0.0]]).repeat(n, 1)
        else:
            self.gate_midpoints = torch.tensor(
                [[[5.0, 0.0], [15.0, 0.0], [40.0, 0.0]]]
            ).repeat(n, 1, 1)
            self.gate_normals = torch.tensor(
                [[[1.0, 0.0], [1.0, 0.0], [1.0, 0.0]]]
            ).repeat(n, 1, 1)
            self.berth_point = torch.tensor([[60.0, 0.0]]).repeat(n, 1)
            self.dock_heading = torch.tensor([[1.0, 0.0]]).repeat(n, 1)
            self.phase = torch.zeros(n, dtype=torch.long) if phase is None else phase
            if publish_exit_progress:
                self._exit_gate_progress = (
                    torch.zeros(n, dtype=torch.long)
                    if exit_progress is None
                    else exit_progress
                )

    def _com_xy(self):
        return self.robot.data.root_com_pos_w[:, :2]

    def _forward_2d(self):
        return torch.stack((torch.cos(self._yaw), torch.sin(self._yaw)), dim=-1)


def test_bridge_reads_the_docking_family():
    env = _StubBerthEnv(
        "dock",
        com_xy=torch.tensor([[-4.0, 1.0]]),
        yaw=torch.tensor([0.5]),
        velocity=torch.tensor([[1.0, 0.0]]),
        yaw_rate=torch.tensor([0.25]),
    )
    assert eval_mppi._detect_mode(env) == "dock"
    bridge = eval_mppi.EnvBridge(torch, env, "dock")
    assert bridge.goal_radius == BERTH_RADIUS
    targets, active = bridge.targets()
    assert targets.shape == (1, 1, 2) and active is None
    assert torch.equal(targets[:, 0, :], env.dock_point)
    assert torch.equal(bridge.dock_heading(), env.dock_heading)
    state = bridge.state()
    assert state.shape == (1, 6)
    # The COM, not the USD origin: the stub puts them 1 m apart on purpose.
    assert torch.allclose(state[:, :2], env._com_xy())
    assert not torch.allclose(state[:, :2], env.robot.data.root_pos_w[:, :2])
    assert abs(float(state[0, 2]) - 0.5) < 1.0e-6, "yaw must come from the bow"
    assert abs(float(state[0, 5]) - 0.25) < 1.0e-6, "yaw rate must survive"
    # Body-frame surge/sway of a 1 m/s +x world velocity at yaw 0.5 rad.
    assert abs(float(state[0, 3]) - math.cos(0.5)) < 1.0e-6
    assert abs(float(state[0, 4]) + math.sin(0.5)) < 1.0e-6


def test_bridge_reads_the_harbor_mission_family():
    env = _StubBerthEnv("mission", com_xy=torch.tensor([[1.0, 0.0]]),
                        yaw=torch.zeros(1))
    assert eval_mppi._detect_mode(env) == "mission"
    bridge = eval_mppi.EnvBridge(torch, env, "mission")
    assert bridge.goal_radius == BERTH_RADIUS
    assert bridge.gate_half_width_m == GATE_HALF_WIDTH_M
    assert bridge.gate_min_normal_speed_mps == GATE_MIN_NORMAL_SPEED_MPS
    targets, active = bridge.targets()
    # Three ordered gates then the berth, in WORLD frame and in that order.
    assert targets.shape == (1, 4, 2)
    assert torch.equal(targets[:, :3, :], env.gate_midpoints)
    assert torch.equal(targets[:, 3, :], env.berth_point)
    assert torch.equal(bridge.gate_normals(), env.gate_normals)
    assert int(active[0]) == 0


def test_bridge_mission_leg_follows_the_env_automaton():
    """phase + _exit_gate_progress -> which of the four legs is active."""
    cases = (
        ((0, 0), 0),  # heading for the first exit gate
        ((0, 1), 1),  # first gate crossed, second exit gate active
        ((1, 1), 2),  # M1 latched: the field-exit gate is active
        ((2, 2), 3),  # M2 latched: the berth
        ((3, 2), 3),  # mission complete: stay parked on the berth
    )
    for (phase, progress), expected in cases:
        env = _StubBerthEnv(
            "mission",
            com_xy=torch.tensor([[1.0, 0.0]]),
            yaw=torch.zeros(1),
            phase=torch.tensor([phase]),
            exit_progress=torch.tensor([progress]),
        )
        bridge = eval_mppi.EnvBridge(torch, env, "mission")
        _targets, active = bridge.targets()
        assert int(active[0]) == expected, (
            f"phase={phase} progress={progress} -> leg {int(active[0])}, "
            f"want {expected}"
        )


def test_bridge_mission_leg_geometric_fallback():
    """Without the env counter, fall back on the first gate plane and SAY so."""
    before = _StubBerthEnv(
        "mission", com_xy=torch.tensor([[1.0, 0.0]]), yaw=torch.zeros(1),
        publish_exit_progress=False,
    )
    after = _StubBerthEnv(
        "mission", com_xy=torch.tensor([[9.0, 0.0]]), yaw=torch.zeros(1),
        publish_exit_progress=False,
    )
    assert not hasattr(before, "_exit_gate_progress")
    assert int(eval_mppi.EnvBridge(torch, before, "mission").targets()[1][0]) == 0
    assert int(eval_mppi.EnvBridge(torch, after, "mission").targets()[1][0]) == 1


# 3b-v. The state bridge: WHICH REFERENCE POINT each family is handed
#
# EnvBridge decides what state the controller sees. An adversarial review
# applied three independent mutations to it and every test in this file stayed
# green, so this section exists to fail under each of them:
#
#   N1  feed the certified families the center of mass instead of the
#       reference point they currently get (fallback -> root_com_pos_w)
#   N2  delete the _com_xy helper branch entirely
#   N3  make the docking path read the USD asset origin (dock/mission branch
#       -> root_pos_w)
#
# N3 is the dangerous one and it is not hypothetical: docking scores position
# at the CENTER OF MASS with a 2.5 m tolerance while the boat asset's USD
# origin sits ~1.0 m away (docking_env.py:630-637, "probed 2026-07-16; broke
# both PID and RL"). A 1 m reference-point error is 40% of the tolerance, so
# it buys plausible-looking WRONG docking numbers, not a crash. No docking
# evaluation has been run yet, which is why this is pinned before one is.

# The probed offset between the boat asset's USD body origin and its center of
# mass (docking_env.py:630-637). The stubs below place the two points exactly
# this far apart so a bridge reading the wrong one cannot land on the right
# answer by coincidence.
_ASSET_ORIGIN_OFFSET_M = 1.0

# (family dir, env module, docstring label, bridge mode, publishes _com_xy,
#  the world accessor that family's OWN success predicate ultimately reads).
# test_bridge_reference_points_match_the_env_sources re-derives the last two
# columns from tasks/, so this table is checked against the deployed envs
# rather than asserted.
_REFERENCE_POINT_TRUTH = (
    ("path_following", "path_following_env.py", "PathFollow",
     "gates", False, "root_pos_w"),
    ("path_hazard", "path_hazard_env.py", "PathHazard",
     "gates", True, "root_com_pos_w"),
    ("station_keeping", "station_keeping_env.py", "StationKeep",
     "hold", False, "root_pos_w"),
    ("hazard_nav", "hazard_nav_env.py", "HazardNav",
     "goal", True, "root_com_pos_w"),
    ("docking", "docking_env.py", "Docking",
     "dock", False, "root_com_pos_w"),
    ("harbor_mission", "harbor_mission_env.py", "HarborMission",
     "mission", True, "root_com_pos_w"),
)

# Which families publish the two bow helpers EnvBridge.state() prefers, so the
# stubs take the same code path the real env would. Checked against the
# sources by test_bridge_reference_points_match_the_env_sources.
_FORWARD_2D_FAMILIES = ("hazard_nav", "docking", "harbor_mission")
_ROOT_QUAT_FAMILIES = ("path_hazard", "hazard_nav", "harbor_mission")

# Helpers a success predicate may reach the world accessor through; the
# resolver below follows each one hop until it reaches root_pos_w or
# root_com_pos_w.
_HOP_HELPERS = ("_com_xy", "_horizontal_distance", "_task_state", "_dock_state")


def _env_source_path(family: str, module: str) -> str:
    return os.path.join(TASKS_DIR, family, module)


def _function_bodies(path: str) -> dict:
    source = open(path, "r", encoding="utf-8").read()
    tree = ast.parse(source, filename=path)
    bodies = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            bodies[node.name] = ast.get_source_segment(source, node) or ""
    return bodies


def _world_accessors(body: str) -> set:
    """Which of the two world position accessors this source text reads."""
    found = set()
    if "root_com_pos_w" in body:
        found.add("root_com_pos_w")
    if re.search(r"(?<!com_)root_pos_w", body):
        found.add("root_pos_w")
    return found


def _scored_accessors(bodies: dict, entry: str = "_get_dones") -> set:
    """Resolve the accessor the episode-scoring path ultimately reads."""
    found: set = set()
    pending = [entry]
    seen: set = set()
    while pending:
        name = pending.pop()
        if name in seen or name not in bodies:
            continue
        seen.add(name)
        body = bodies[name]
        found |= _world_accessors(body)
        for helper in _HOP_HELPERS:
            if f"self.{helper}()" in body:
                pending.append(helper)
    return found


def test_bridge_reference_points_match_the_env_sources():
    """Re-derive the reference-point table from tasks/, do not assert it.

    Every claim EnvBridge.position_xy makes about a family is checked here
    against the deployed env source: whether the family publishes _com_xy,
    what _com_xy returns, and which world accessor the block that latches
    episode_success ultimately reads. Skipped only when tasks/ is not
    deployed beside scripts/ (the boxes ship the script pair alone).
    """
    present = [
        row for row in _REFERENCE_POINT_TRUTH
        if os.path.exists(_env_source_path(row[0], row[1]))
    ]
    if not present:
        print("\n[NOTE] tasks/ not present; reference-point cross-check skipped")
        return
    assert len(present) == len(_REFERENCE_POINT_TRUTH), (
        "some env sources are missing; refusing a partial cross-check: "
        f"{sorted(set(r[0] for r in _REFERENCE_POINT_TRUTH) - set(r[0] for r in present))}"
    )
    for family, module, _label, _mode, publishes, scored in present:
        bodies = _function_bodies(_env_source_path(family, module))
        assert ("_com_xy" in bodies) is publishes, (
            f"{family}: publishes _com_xy is {'_com_xy' in bodies}, table "
            f"says {publishes}"
        )
        if publishes:
            assert _world_accessors(bodies["_com_xy"]) == {"root_com_pos_w"}, (
                f"{family}._com_xy no longer returns the center of mass: "
                f"{bodies['_com_xy']}"
            )
        got = _scored_accessors(bodies)
        assert got == {scored}, (
            f"{family}: the success path reads {sorted(got)}, table says "
            f"{scored} -- EnvBridge.position_xy may now hand this family the "
            "wrong reference point"
        )
        assert (family in _FORWARD_2D_FAMILIES) == ("_forward_2d" in bodies), (
            f"{family}: _forward_2d publication drifted from the stub table"
        )
        assert (family in _ROOT_QUAT_FAMILIES) == ("_root_quat" in bodies), (
            f"{family}: _root_quat publication drifted from the stub table"
        )


def test_bridge_docstring_states_the_true_reference_point_per_family():
    """The in-code table must say what the envs actually do.

    An earlier version of this comment claimed the certified families keep
    root_pos_w "because that is the reference point their OWN predicates
    score". That was wrong for HazardNav and PathHazard, which are certified,
    publish _com_xy, and score at the center of mass. A comment that
    overstates correctness is worse than no comment, so it is pinned.
    """
    doc = eval_mppi.EnvBridge.position_xy.__doc__
    assert doc, "EnvBridge.position_xy lost its reference-point table"
    for _family, _module, label, _mode, publishes, scored in _REFERENCE_POINT_TRUTH:
        row = re.search(
            rf"^\s*{label}\s+(YES|no)\s+(root_com_pos_w|root_pos_w)\b",
            doc,
            re.M,
        )
        assert row, f"the docstring table has no row for {label}"
        assert (row.group(1) == "YES") is publishes, (
            f"{label}: docstring says publishes _com_xy = {row.group(1)!r}"
        )
        assert row.group(2) == scored, (
            f"{label}: docstring says scored at {row.group(2)}, the env source "
            f"says {scored}"
        )


class _StubScene:
    def __init__(self, num_envs):
        self.env_origins = torch.zeros((num_envs, 3))


class _FamilyCfg:
    """Only the cfg fields the family's DEPLOYED cfg really declares.

    Deliberately NOT a superset. StationKeep declares hold_radius and no
    goal_radius (station_keeping_env_cfg.py:194); the two berthing families
    declare both, with harbor_mission_env_cfg.py:284-285 enforcing the alias;
    the gate window exists only on the harbor cfg (:170-172). So a bridge that
    reads the wrong field for a family raises AttributeError here instead of
    quietly picking up a value the real env would never have had.
    """

    def __init__(self, mode):
        if mode == "hold":
            self.hold_radius = GOAL_RADIUS
        elif mode in ("dock", "mission"):
            self.success_position_tolerance_m = BERTH_RADIUS
            self.goal_radius = BERTH_RADIUS
            if mode == "mission":
                self.gate_half_width_m = GATE_HALF_WIDTH_M
                self.gate_min_normal_speed_mps = GATE_MIN_NORMAL_SPEED_MPS
        else:
            self.goal_radius = GOAL_RADIUS


class _FamilyData:
    """robot.data with the COM and the USD body origin held 1 m apart."""

    def __init__(self, com_xy, yaw):
        n = com_xy.shape[0]
        self.root_com_pos_w = torch.cat((com_xy, torch.zeros((n, 1))), dim=1)
        self.root_pos_w = self.root_com_pos_w + torch.tensor(
            [_ASSET_ORIGIN_OFFSET_M, 0.0, 0.0]
        )
        self.root_com_vel_w = torch.zeros((n, 6))
        self.root_ang_vel_w = torch.zeros((n, 3))
        # wxyz quaternion of a pure yaw, for the families that publish neither
        # _forward_2d nor _root_quat and so leave through _quat_rotate.
        self.root_link_quat_w = torch.stack(
            (
                torch.cos(yaw / 2.0),
                torch.zeros_like(yaw),
                torch.zeros_like(yaw),
                torch.sin(yaw / 2.0),
            ),
            dim=-1,
        )


class _StubFamilyEnv:
    """Stand-in for one deployed family, exposing exactly what EnvBridge reads.

    Attribute-for-attribute faithful on the two things the mutations hide
    behind: whether the family publishes _com_xy (docking does NOT, which is
    why the dock branch exists at all) and which bow helper it publishes.
    """

    def __init__(self, family, mode, publishes_com_xy, com_xy, yaw):
        n = com_xy.shape[0]
        self.family = family
        self.cfg = _FamilyCfg(mode)
        self.num_envs = n
        self.robot = _StubRobot(_FamilyData(com_xy, yaw))
        self.scene = _StubScene(n)
        self.forward_vec = torch.zeros((n, 3))
        self.forward_vec[:, 0] = 1.0
        self._yaw = yaw
        if publishes_com_xy:
            self._com_xy = self._com_xy_impl
        if family in _FORWARD_2D_FAMILIES:
            self._forward_2d = self._forward_2d_impl
        if family in _ROOT_QUAT_FAMILIES:
            self._root_quat = self._root_quat_impl
        if mode == "gates":
            self.waypoints = torch.tensor([[[10.0, 0.0], [20.0, 0.0]]]).repeat(n, 1, 1)
            self.gates_passed = torch.zeros(n, dtype=torch.long)
        elif mode == "hold":
            self.hold_point = torch.zeros((n, 2))
        elif mode == "goal":
            self.goal_radius = GOAL_RADIUS
            self.target_pos = torch.tensor([[12.0, 0.0]]).repeat(n, 1)
        elif mode == "dock":
            self.dock_point = torch.zeros((n, 2))
            self.dock_heading = torch.tensor([[1.0, 0.0]]).repeat(n, 1)
        else:
            self.gate_midpoints = torch.tensor(
                [[[5.0, 0.0], [15.0, 0.0], [40.0, 0.0]]]
            ).repeat(n, 1, 1)
            self.gate_normals = torch.tensor(
                [[[1.0, 0.0], [1.0, 0.0], [1.0, 0.0]]]
            ).repeat(n, 1, 1)
            self.berth_point = torch.tensor([[60.0, 0.0]]).repeat(n, 1)
            self.dock_heading = torch.tensor([[1.0, 0.0]]).repeat(n, 1)
            self.phase = torch.zeros(n, dtype=torch.long)
            self._exit_gate_progress = torch.zeros(n, dtype=torch.long)

    def _com_xy_impl(self):
        return self.robot.data.root_com_pos_w[:, :2]

    def _forward_2d_impl(self):
        return torch.stack((torch.cos(self._yaw), torch.sin(self._yaw)), dim=-1)

    def _root_quat_impl(self):
        return self.robot.data.root_link_quat_w


def _stub_for(family: str, com_xy, yaw) -> _StubFamilyEnv:
    """Build the stub for one family STRICTLY from the cross-checked table.

    Nothing about a family is hard-coded at a call site, so the chain runs
    deployed env source -> _REFERENCE_POINT_TRUTH (checked by
    test_bridge_reference_points_match_the_env_sources) -> stub -> bridge.
    """
    row = next(r for r in _REFERENCE_POINT_TRUTH if r[0] == family)
    return _StubFamilyEnv(row[0], row[3], row[4], com_xy, yaw)


def test_bridge_hands_every_family_its_own_scored_reference_point():
    """The whole point of the bridge, one row per deployed family.

    Fails under all three review mutations:
      N1 (fallback -> COM)          breaks PathFollow and StationKeep
      N2 (delete the helper branch) breaks HazardNav and PathHazard
      N3 (dock branch -> origin)    breaks Docking
    The COM and the USD origin are 1 m apart in every stub, so no row can
    pass by reading the wrong point.
    """
    com_xy = torch.tensor([[-4.0, 1.0], [7.5, -2.25]])
    yaw = torch.tensor([0.5, -1.1])
    for family, _module, _label, mode, _publishes, scored in _REFERENCE_POINT_TRUTH:
        env = _stub_for(family, com_xy, yaw)
        assert eval_mppi._detect_mode(env) == mode, (
            f"{family}: detection resolved {eval_mppi._detect_mode(env)!r}, "
            f"not {mode!r}"
        )
        data = env.robot.data
        want = (
            data.root_com_pos_w[:, :2] if scored == "root_com_pos_w"
            else data.root_pos_w[:, :2]
        )
        other = (
            data.root_pos_w[:, :2] if scored == "root_com_pos_w"
            else data.root_com_pos_w[:, :2]
        )
        assert float((want - other).norm(dim=-1).min()) > 0.5, (
            "the stub's two reference points are not separated"
        )
        bridge = eval_mppi.EnvBridge(torch, env, mode)
        got = bridge.position_xy()
        assert torch.equal(got, want), (
            f"{family} ({mode}): the bridge hands the controller "
            f"{got.tolist()}, but the env scores this family at {scored} "
            f"= {want.tolist()}"
        )
        assert not torch.equal(got, other), f"{family}: read the wrong point"
        state = bridge.state()
        assert state.shape == (2, 6)
        assert torch.equal(state[:, :2], want), (
            f"{family}: state() disagrees with position_xy()"
        )
        for i in range(2):
            assert abs(float(state[i, 2]) - float(yaw[i])) < 1.0e-5, (
                f"{family}: yaw {float(state[i, 2])} != {float(yaw[i])}"
            )


def test_bridge_docking_stub_has_no_com_helper_like_the_real_env():
    """The stub must not hand docking a helper the deployed env lacks.

    This is the exact hole the N3 mutation hid in: a docking fixture that
    publishes _com_xy never reaches the dock branch, so swapping that branch
    to the USD origin changes nothing anyone can observe. The stub's helper
    surface comes from the table the env sources are checked against, so this
    cannot be re-broken by editing a call site.
    """
    dock = _stub_for("docking", torch.tensor([[-4.0, 1.0]]), torch.tensor([0.5]))
    assert not hasattr(dock, "_com_xy"), (
        "the docking stub publishes _com_xy; the real docking env does not, "
        "and with it the dock branch of position_xy is never exercised"
    )
    bridge = eval_mppi.EnvBridge(torch, dock, "dock")
    got = bridge.position_xy()
    assert torch.equal(got, dock.robot.data.root_com_pos_w[:, :2]), (
        f"the dock branch hands the controller {got.tolist()}; docking scores "
        f"at the COM {dock.robot.data.root_com_pos_w[:, :2].tolist()}, and the "
        f"USD origin is {dock.robot.data.root_pos_w[:, :2].tolist()}"
    )
    # And the miss a wrong branch would cause is a large fraction of the
    # berthing tolerance, not a rounding error.
    error = float(
        (dock.robot.data.root_pos_w[:, :2]
         - dock.robot.data.root_com_pos_w[:, :2]).norm(dim=-1)[0]
    )
    assert error / BERTH_RADIUS > 0.3, (
        f"a {error:.2f} m reference-point error is {error / BERTH_RADIUS:.0%} "
        f"of the {BERTH_RADIUS} m berthing tolerance"
    )


# 3b-vi. Disclosure of water motion the calm-water nominal model cannot see


class _StubSimCfg:
    dt = NOMINAL_BLUEBOAT["physics_dt_s"]


class _StubPhysicsCfg:
    """underwater_physics_cfg, nominal damping plus the current knobs.

    Damping values come from NOMINAL_BLUEBOAT so the guard's hard checks pass
    for the right reason and the test cannot drift away from the deployed
    hull.
    """

    def __init__(self, enable_current=False, speed=(1.0, 1.5), drag=8.0):
        self.surge_lin_damping = NOMINAL_BLUEBOAT["surge_lin"]
        self.surge_quad_damping = NOMINAL_BLUEBOAT["surge_quad"]
        self.sway_lin_damping = NOMINAL_BLUEBOAT["sway_lin"]
        self.sway_quad_damping = NOMINAL_BLUEBOAT["sway_quad"]
        self.yaw_lin_damping = NOMINAL_BLUEBOAT["yaw_lin"]
        self.yaw_quad_damping = NOMINAL_BLUEBOAT["yaw_quad"]
        self.enable_current = enable_current
        self.current_speed_min, self.current_speed_max = speed
        self.current_drag_coeff = drag


class _StubSeaStateCfg:
    def __init__(self, enable=True, hs_range=(0.30, 0.60), tp_range=(1.5, 3.0)):
        self.enable = enable
        self.hs_range = hs_range
        self.tp_range = tp_range


class _StubNominalCfg:
    def __init__(self, physics):
        self.sim = _StubSimCfg()
        self.decimation = NOMINAL_BLUEBOAT["decimation"]
        self.thrust_max_fwd = NOMINAL_BLUEBOAT["thrust_fwd_n"]
        self.thrust_max_rev = NOMINAL_BLUEBOAT["thrust_rev_n"]
        self.yaw_torque_max = NOMINAL_BLUEBOAT["yaw_torque_nm"]
        self.half_beam_m = NOMINAL_BLUEBOAT["half_beam_m"]
        self.underwater_physics_cfg = physics


class _StubVehicleSpec:
    name = "blueboat"


class _StubGuardEnv:
    """Enough of an env for _nominal_guard to run start to finish."""

    def __init__(self, physics, sea_state=None, ramp=None):
        self.vehicle_spec = _StubVehicleSpec()
        self.cfg = _StubNominalCfg(physics)
        self.physics_cfg = physics
        self.num_envs = 2
        self.robot = _StubRobot(_FamilyData(torch.zeros((2, 2)), torch.zeros(2)))
        if sea_state is not None:
            self.cfg.sea_state = sea_state
        if ramp is not None:
            self.cfg.current_ramp_start_mps, self.cfg.current_ramp_end_mps = ramp


def _guard_stdout(env) -> str:
    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        eval_mppi._nominal_guard(env, NOMINAL_BLUEBOAT)
    return buffer.getvalue()


def test_nominal_guard_discloses_a_current_the_model_cannot_see():
    """Dock-Current enables a crossing current; the model is calm water.

    Isaac-USV-Dock-BlueBoat-Current-Direct-v1 is accepted by the widened
    family detection, and its 1.0-1.5 m/s current lives on
    underwater_physics_cfg -- one level below the top-level cfg fields
    SUITE_D_FIELDS inspects -- so it used to reach the controller in total
    silence. Neither silently refused nor silently allowed: disclosed, on the
    same channel and in the same format as every other shift.
    """
    assert "enable_current" not in {name for name, _ in eval_mppi.SUITE_D_FIELDS}, (
        "if the current became a top-level Suite D field this test is stale"
    )
    calm = _StubGuardEnv(_StubPhysicsCfg())
    assert eval_mppi._water_motion_notes(calm) == []
    assert "NOMINAL-MODEL NOTE" not in _guard_stdout(calm), (
        "calm water must not print a mismatch note"
    )

    current = _StubGuardEnv(_StubPhysicsCfg(enable_current=True, speed=(1.0, 1.5)))
    notes = eval_mppi._water_motion_notes(current)
    assert len(notes) == 1, notes
    printed = _guard_stdout(current)
    assert notes[0] in printed, (
        "_nominal_guard no longer prints the water-motion disclosure:\n" + printed
    )
    for fragment in ("NOMINAL-MODEL NOTE", "enable_current=True", "1.00-1.50 m/s",
                     "CALM WATER"):
        assert fragment in printed, (
            f"the current disclosure does not mention {fragment!r}:\n{printed}"
        )
    # Disclosed, not refused: the guard must still return normally.
    eval_mppi._nominal_guard(current, NOMINAL_BLUEBOAT)


def test_current_disclosure_numbers_match_the_deployed_cfg():
    """The speeds this test asserts are the deployed ones, not invented."""
    cfg_path = os.path.join(TASKS_DIR, "docking", "docking_env_cfg.py")
    if not os.path.exists(cfg_path):
        print("\n[NOTE] tasks/docking absent; current-cfg cross-check skipped")
        return
    source = open(cfg_path, "r", encoding="utf-8").read()
    block = re.search(
        r"class DockingBlueBoatCurrentEnvCfg\(.*?\):(.*?)(?=\n@configclass)",
        source + "\n@configclass",
        re.S,
    )
    assert block, "DockingBlueBoatCurrentEnvCfg is gone or was renamed"
    body = block.group(1)
    for expected in (
        "enable_current = True",
        "current_speed_min = 1.0",
        "current_speed_max = 1.5",
    ):
        assert expected in body, (
            f"Dock-Current no longer sets {expected!r}; update the disclosure "
            f"test's numbers:\n{body}"
        )
    # It really is nested under underwater_physics_cfg, which is why the
    # top-level SUITE_D_FIELDS loop cannot reach it.
    assert "underwater_physics_cfg.enable_current" in body, body


def test_ramping_current_and_sea_state_are_disclosed_too():
    """The same mismatch on the other water-motion variants."""
    ramp = _StubGuardEnv(
        _StubPhysicsCfg(enable_current=True, speed=(2.0, 2.5)),
        ramp=(0.5, 3.0),
    )
    notes = eval_mppi._water_motion_notes(ramp)
    assert len(notes) == 2, notes
    assert "2.00-2.50 m/s" in notes[0]
    assert "RAMPS" in notes[1] and "0.50 -> 3.00 m/s" in notes[1], notes[1]

    waves = _StubGuardEnv(_StubPhysicsCfg(), sea_state=_StubSeaStateCfg())
    notes = eval_mppi._water_motion_notes(waves)
    assert len(notes) == 1, notes
    assert "sea_state.enable=True" in notes[0] and "no wave term" in notes[0]

    off = _StubGuardEnv(
        _StubPhysicsCfg(), sea_state=_StubSeaStateCfg(enable=False)
    )
    assert eval_mppi._water_motion_notes(off) == []


# 3b-iii. Bit-identity of the three certified modes


# Executed actions from three fixed scenarios, captured from
# scripts/mppi_controller.py BEFORE the dock and mission modes were added
# (2026-08-24; CPU float32; verified byte-stable at 1 and 16 torch threads).
# float32 little-endian bytes of a [3 control steps, 2 envs, 2] tensor.
_CERTIFIED_MODE_ACTIONS = {
    "gates": (
        "885d873e1f7887bef6751d3e76637cbe245ab13e204087bbbb517c3e37679a3d"
        "eb68c9be2ae3a6be655eaa3e2e671c3d"
    ),
    "goal": (
        "b9993ebe6c84b8bec952b6bcb54699be637d8ebea90b983e6060c9be589598be"
        "7d463dbe3fc8cb3c16845b3eb4d037be"
    ),
    "hold": (
        "73e358bda02ba13eac37103c98997fbe0c80b4be421fe13e50b454bd1b6abdbe"
        "7831e7beec9dcdbee9775d3ea08f8fbb"
    ),
}


def _certified_mode_actions(mode: str, seed: int, **overrides) -> torch.Tensor:
    """Replay one fixed scenario per certified mode; return [3, 2, 2]."""
    controller = MPPIController(
        num_envs=2,
        device=DEVICE,
        params=MPPIParams(K=8, H=5, seed=seed, **overrides),
    )
    state = torch.zeros((2, 6))
    state[0] = torch.tensor([0.0, 0.0, 0.0, 1.0, 0.0, 0.0])
    state[1] = torch.tensor([-3.0, 2.0, 0.5, 0.5, -0.1, 0.2])
    if mode == "gates":
        targets = torch.tensor(
            [[[10.0, 0.0], [10.0, 8.0]], [[6.0, 1.0], [12.0, 4.0]]]
        )
        active = torch.tensor([0, 1])
        centers = radii = None
    elif mode == "goal":
        targets = torch.tensor([[[12.0, 0.0]], [[9.0, -2.0]]])
        active = None
        centers = torch.tensor([[[5.0, 0.5]], [[2.0, 1.0]]])
        radii = torch.tensor([[1.2], [0.9]])
    else:
        targets = torch.tensor([[[2.0, 0.0]], [[-1.0, 1.0]]])
        active = None
        centers = radii = None
    actions = []
    for _ in range(3):
        action, _info = controller.rollout(
            state, targets=targets, active_index=active,
            goal_radius=GOAL_RADIUS, mode=mode,
            obstacle_centers=centers, obstacle_radii=radii,
        )
        actions.append(action.clone())
        state = controller.dynamics.step(state, action)
    return torch.stack(actions)


def test_regression_certified_modes_bit_identical():
    """gates / hold / goal must be BIT-identical to the pre-docking code.

    Thirty-plus certified dual-seed numbers were produced with those three
    cost modes. Adding dock and mission may not perturb them by one ULP, so
    this replays fixed scenarios and compares raw float32 bytes -- not an
    allclose -- against fixtures captured before the change.
    """
    for mode, seed in (("gates", 11), ("goal", 12), ("hold", 13)):
        produced = _certified_mode_actions(mode, seed).numpy().tobytes().hex()
        assert produced == _CERTIFIED_MODE_ACTIONS[mode], (
            f"{mode} mode is no longer bit-identical to the certified "
            f"controller:\n  now {produced}\n  was {_CERTIFIED_MODE_ACTIONS[mode]}"
        )


def test_regression_new_weights_cannot_reach_the_certified_modes():
    """Absurd dock weights must not move a gates/hold/goal action at all.

    The bit-fixture above proves the SHIPPED defaults changed nothing; this
    proves the new terms are unreachable from those cost paths rather than
    merely small, so a future retune of the berthing weights cannot silently
    invalidate a certified PathFollow / StationKeep / HazardNav number.
    """
    for mode, seed in (("gates", 11), ("goal", 12), ("hold", 13)):
        baseline = _certified_mode_actions(mode, seed)
        perturbed = _certified_mode_actions(
            mode, seed, w_dock_heading=999.0, w_dock_speed=999.0
        )
        assert torch.equal(perturbed, baseline), (
            f"{mode} mode reads the dock pose weights"
        )


# 3c. Wall clock


def _time_per_step(n, K, H, num_obstacles=0, steps=20) -> float:
    controller = _make_controller(n, K=K, H=H, seed=1)
    state = _rest_state(n)
    targets = torch.zeros((n, 1, 2))
    targets[:, 0, 0] = 15.0
    centers = radii = None
    if num_obstacles:
        centers = torch.rand((n, num_obstacles, 2)) * 30.0 + 20.0
        radii = torch.full((n, num_obstacles), 0.8)
    for _ in range(3):  # warmup
        controller.rollout(
            state, targets=targets, active_index=None,
            goal_radius=GOAL_RADIUS, mode="goal",
            obstacle_centers=centers, obstacle_radii=radii,
        )
    start = time.perf_counter()
    for _ in range(steps):
        controller.rollout(
            state, targets=targets, active_index=None,
            goal_radius=GOAL_RADIUS, mode="goal",
            obstacle_centers=centers, obstacle_radii=radii,
        )
    return (time.perf_counter() - start) / steps * 1000.0


def test_wall_clock_cpu_64env_256k_30h():
    ms_open = _time_per_step(64, 256, 30, num_obstacles=0)
    ms_hazard = _time_per_step(64, 256, 30, num_obstacles=96)
    default_h = MPPIParams().H
    ms_default = _time_per_step(64, 256, default_h, num_obstacles=96)
    print(
        f"\n[WALL-CLOCK CPU] N=64 K=256 H=30: {ms_open:.1f} ms/control-step "
        f"open water, {ms_hazard:.1f} ms with 96 obstacles; "
        f"shipped default H={default_h}: {ms_default:.1f} ms with 96 obstacles "
        f"({torch.get_num_threads()} torch threads)"
    )
    assert ms_open < 1500.0, f"open-water step {ms_open:.0f} ms is seconds-slow"
    assert ms_hazard < 3000.0, f"obstacle step {ms_hazard:.0f} ms is seconds-slow"
    assert ms_default < 6000.0, f"default-H step {ms_default:.0f} ms is seconds-slow"


# ---------------------------------------------------------------- runner


def main() -> int:
    tests = [
        (name, fn)
        for name, fn in sorted(globals().items())
        if name.startswith("test_") and callable(fn)
    ]
    failures = 0
    for name, fn in tests:
        start = time.perf_counter()
        try:
            fn()
        except Exception as exc:
            failures += 1
            print(f"FAIL {name}: {type(exc).__name__}: {exc}")
        else:
            print(f"PASS {name} ({time.perf_counter() - start:.1f}s)")
    print(f"test_mppi_cpu: {len(tests)} tests, {failures} failure(s)")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
